### ISSUE TITLE
Release 1.6.1 not available at maven.org

### ISSUE THREAD

**Issue by mkonietzka** [barend/java-iban#16]
Release 1.6.1 is not available at maven.org.
https://repo1.maven.org/maven2/nl/garvelink/oss/iban/
reports as 1.6.0 as latest.
It is only available via nexus in the repository nlgarvelink-1009 (staging: closed)
https://oss.sonatype.org/index.html#nexus-search;quick~nl.garvelink

**Comment by mkonietzka** [comment]
Is available now. 👍

**Comment by barend** [comment]
Yep. I missed a step in my checklist 🤦‍♂. That's now completed. Thanks for the heads-up!
