### ISSUE TITLE
Can this convert from national to IBAN format?

### ISSUE THREAD

**Issue by breakline87** [barend/java-iban#25]
Didn't see it in the usage part. Does it only handle numbers already in IBAN format?

**Comment by barend** [comment]
This library doesn't do that conversion. It can calculate the check digits using the so named function in the `Modulo97` class, but I have kept the country specific bits outside my scope. You might try the [iban4j](https://github.com/arturmkrtchyan/iban4j) project, their scope is larger than mine and they may support this.

**Comment by breakline87** [comment]
Thank you
